### ISSUE TITLE
The problem of data allocation

### ISSUE THREAD

**Issue by CongjiangCST** [panjingyu/Decentralized-Routability-Estimation#1]
Running `alloc.py`, the PKL file reads a tuple file that contains three lists, so 

`d. update (pickle.load (file))`

reports an error: `ValueError: dictionary update sequence element # 0has length XXX; 2is required. `
Are there any PKL preprocessing files that are missing?

**Comment by panjingyu** [comment]
Hi, it should be fixed after commit https://github.com/panjingyu/Decentralized-Routability-Estimation/commit/adab6fd4777b73f143152220810c2a83ce830a14.

Thanks for pointing out!

**Comment by mjm65688** [comment]
> Running `alloc.py`, the PKL file reads a tuple file that contains three lists, so
> 
> `d. update (pickle.load (file))`
> 
> reports an error: `ValueError: dictionary update sequence element # 0has length XXX; 2is required. ` Are there any PKL preprocessing files that are missing?

Hello，excuse me, would you mind adding my contact information(wechat:mjm65688) for communicating each other about the  implementation of this project? Thanks a lot.
